# Generated by Django 4.1.2 on 2023-01-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='techteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_name', models.CharField(max_length=50)),
                ('tt_twitter', models.URLField(default='some_value')),
                ('tt_insta', models.URLField(default='some_value')),
                ('tt_linkedin', models.URLField(default='some_value')),
                ('tt_teamname', models.CharField(max_length=50)),
                ('tt_image', models.FileField(default=None, max_length=250, null=True, upload_to='')),
                ('tt_shortdesc', models.TextField()),
            ],
        ),
    ]
