# Generated by Django 4.1.2 on 2023-01-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techteam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techteam',
            name='tt_twitter',
        ),
    ]
