# Generated by Django 4.1.2 on 2023-01-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contentteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_name', models.CharField(max_length=50)),
                ('ct_insta', models.URLField(default='some_value')),
                ('ct_linkedin', models.URLField(default='some_value')),
                ('ct_teamname', models.CharField(max_length=50)),
                ('ct_image', models.FileField(default=None, max_length=250, null=True, upload_to='')),
                ('ct_shortdesc', models.TextField()),
            ],
        ),
    ]
