# Generated by Django 4.1.2 on 2023-01-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact1',
        ),
    ]
