# Generated by Django 4.1.2 on 2023-01-28 14:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('blog_shortdecs', models.TextField()),
                ('blog_desc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.DeleteModel(
            name='blogs',
        ),
    ]
