# Generated by Django 4.1.2 on 2023-01-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_image',
            field=models.ImageField(default='some_value', upload_to=None),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_insta',
            field=models.URLField(default='some_value'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_linkedin',
            field=models.URLField(default='some_value'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_twitter',
            field=models.URLField(default='some_value'),
        ),
    ]
