# Generated by Django 4.1.2 on 2023-01-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_lead_image_lead_lead_insta_lead_lead_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_image',
            field=models.ImageField(default='some_value', upload_to=''),
        ),
    ]
